version: "3.8"
services:
  user_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movie_ticket_booking_user_service_db
    restart: always
    volumes:
      - ../db-data/user_service:/var/lib/postgresql/data

  movie_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movie_ticket_booking_movie_service_db
    restart: always
    volumes:
      - ../db-data/movie_service:/var/lib/postgresql/data

  booking_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movie_ticket_booking_booking_service_db
    restart: always
    volumes:
      - ../db-data/booking_service:/var/lib/postgresql/data

  payment_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movie_ticket_booking_payment_service_db
    restart: always
    volumes:
      - ../db-data/payment_service:/var/lib/postgresql/data
    
  notification_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5436:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movie_ticket_booking_notification_service_db
    restart: always
    volumes:
      - ../db-data/notification_service:/var/lib/postgresql/data

  zookeeper:
    image: 'bitnami/zookeeper:3.8-debian-10'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always

  kafka:
    image: 'bitnami/kafka:3.1-debian-10'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: always

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    restart: always
    volumes:
      - ../minio-data:/data 

  redis:
    image: redis:7.2.4
    restart: always
    ports:
    - "6379:6379"
