version: "3.8"
services:
  user_service_db:
    image: "postgres:14.2-bullseye"
    ports:
      - "5432:5432"
    env_file: 
      - ../config/.user_service_db.env
    restart: always
    networks:
      - intranet
    volumes:
      - ../db-data/user_service:/var/lib/postgresql/data

  movie_service_db:
    image: "postgres:14.2-bullseye"
    ports:
      - "5433:5432"
    env_file: 
      - ../config/.movie_service_db.env
    restart: always
    networks:
      - intranet
    volumes:
      - ../db-data/movie_service:/var/lib/postgresql/data

  booking_service_db:
    image: "postgres:14.2-bullseye"
    ports:
      - "5434:5432"
    env_file: 
      - ../config/.booking_service_db.env
    restart: always
    networks:
      - intranet
    volumes:
      - ../db-data/booking_service:/var/lib/postgresql/data
  
  payment_service_db:
    image: "postgres:14.2-bullseye"
    ports:
      - "5435:5432"
    env_file: 
      - ../config/.payment_service_db.env
    restart: always
    networks:
      - intranet
    volumes:
      - ../db-data/payment_service:/var/lib/postgresql/data

  stripe-cli:
    image: stripe/stripe-cli
    command: listen --api-key sk_test_51P6wPQP8gU29IW1UUuoTwgIr7S53CY3B9bPXkLvOJQAhlW1XeBK95avwaX03VcR760BmvarFq4itDgmt0PCxUf6m00HQ3ObFsm  --events checkout.session.completed,checkout.session.expired --forward-to http://payment_service:4242/webhook
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - default
      - intranet
    ports:
      - "4242:4242"
  
  zookeeper:
    image: "bitnami/zookeeper:3.8-debian-10"
    env_file:
      - ../config/.zookeeper.env
    restart: always
    networks:
      - intranet
    volumes:
      - ../zookeeper-data:/bitnami/zookeeper

  kafka:
    image: "bitnami/kafka:3.1-debian-10"
    env_file:
      - ../config/.kafka.env
    depends_on:
      - zookeeper
    restart: always
    networks:
      - intranet
    volumes:
      - ../kafka-data:/bitnami/kafka

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
    env_file:
      - ../config/.minio.env
    restart: always
    networks:
      - intranet
    volumes:
      - ../minio-data:/data 

  redis:
    image: redis:7.2.4
    restart: always
    networks:
      - intranet
    volumes:
      - ../redis-data:/data

  gateway:
    build: ../gateway
    ports:
      - "8080:8080"
    env_file:
      - ../config/.gateway.env
    depends_on:
      - user_service
      - movie_service
      - booking_service
      - payment_service
      - minio
    networks:
      - default
      - intranet  
    restart: always
  
  user_service:
    build: ../UserService
    env_file:
      - ../config/.user_service.env
    depends_on:
      - user_service_db
    networks:
      - intranet
    restart: always

  movie_service:
    build: ../MovieService
    env_file:
      - ../config/.movie_service.env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - movie_service_db
      - minio
      - kafka
    networks:
      - intranet
    restart: always

  booking_service:
    build: ../BookingService
    env_file:
      - ../config/.booking_service.env
    depends_on:
      - booking_service_db
      - kafka
      - redis
      - movie_service
      - user_service
    networks:
      - intranet
    restart: always
  
  payment_service:
    build: ../PaymentService
    env_file:
      - ../config/.payment_service.env
    depends_on:
      - payment_service_db
      - kafka
      - booking_service
      - movie_service
    networks:
      - intranet
    restart: always

networks:
  intranet: {}
  default: {}

      